version: '3.8'

services:
  todoapp-api:
    build:
      context: .
      dockerfile: ToDoApp.Api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ToDoApp.Api/todo.sql:/app/todo.sql
      - ./data-protection-keys:/home/app/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  todoapp-ui:
    build:
      context: .
      dockerfile: ToDoApp.UI/Dockerfile
    ports:
      - "5225:5225"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5225
      - TODO_API_URL=http://todoapp-api:8080
networks:
  default:
    driver: bridge
