version: '3.8'

services:
  todoapp-api:
    build:
      context: .
      dockerfile: ToDoApp.Api/Dockerfile
    ports:
      - "8080:80"  # Sesuaikan dengan port yang digunakan dalam Dockerfile
    volumes:
      - ./ToDoApp.Api/todo.sql:/app/todo.sql
      - ./data-protection-keys:/home/app/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  todoapp-ui:
    build:
      context: .
      dockerfile: ToDoApp.UI/Dockerfile 
    ports:
      - "8081:80"  # Sesuaikan dengan port yang digunakan dalam Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  default:
    driver: bridge
